[[fbcrypt-utils]]
= Поддержка в консольных утилитах Firebird

Как было описано выше главная проблема при работе с зашифрованными базами данных заключается в том как хранить ключи шифрования? В идеальном случае ключ шифрования должен быть известен только клиентскому приложению, чтобы его невозможно было украсть. Особенно актуально эта проблема для приложений использующих embedded соединения, когда база данных и клиентское приложение расположено на одной и той же машине. Но как в этом случае работать с консольными утилитами Firebird, которым необходимо соединение с БД, такими как `gbak`, `nbackup` и др.

Для того, чтобы использовать встроенные утилиты Firebird и не хранить ключ на сервере, мы модифицировали утилиты `gbak`, `nbackup`, `isql` и `gfix`. Модифицированные утилиты позволяют указывать альтернативный плагин для хранения ключа (`KeyHolder`). Так же был разработан плагин `KeyHolderStdin`, которые позволяет считывать ключ шифрования из входного потока консоли.

Рассмотрим пример работы `gbak` с плагином `KeyHolderStdin`:

[source,cmd]
----
echo Key=Green 0xab,0xd7,0x34,0x63,0xae,0x19,0x52,0x00,0xb8,0x84,0xa3,0x44,0xbd,0x11,0x9f,0x72,0xe0,0x04,0x68,0x4f,0xc4,0x89,0x3b,0x20,0x8d,0x2a,0xa7,0x07,0x32,0x3b,0x5e,0x74, | gbak -b localhost:"C:\Firebird\crypt-plugin\CryptClient\db-crypt\emp-crypted.fdb" "C:\Firebird\crypt-plugin\CryptClient\db-crypt\emp-crypted.fbk" -KeyHolder KeyHolderStdin
----

Здесь ключ передаётся из входного потока. Формат передачи ключа следующий:

[source,cmd]
----
echo Key=<KeyName> <key_value>

<key_value> ::= 0x<hex-pair>, [0x<hex-pair>, ...]
----

Здесь `<KeyName>` - имя ключа, которое должно совпадать с именем ключа  используемым при шифровании базы данных.

Обратите внимание, конечная запятая обязательна. Процесс генерации ключей описан в <<fbcrypt-keygen>>.
