:sectnums!:

[preface]
= Зачем нам нужно шифрование баз данных (и когда оно не нужно)?

Шифрование баз данных в Firebird было введено в версии Firebird 3.0 (вместе с шифрованием протокола передачи, которое часто путают с обсуждаемой темой) и значительно расширило возможности защиты данных от несанкционированного доступа. Однако это не панацея, и для его правильного использования необходимо понимать его сильные и слабые стороны. В этой статье мы рассмотрим внутреннее устройство шифрования баз данных на базовом уровне, чтобы дать разработчикам приложений Firebird лучшее понимание того, как работает шифрование баз данных.

== Зачем нам нужно шифрование баз данных?

. Для защиты баз данных с конфиденциальными/ценными данными от "`физической`" кражи. Если злоумышленник украдет диск с копией зашифрованной базы данных или каким-либо образом получит копию файла базы данных, то без соответствующего ключа будет невозможно прочитать из него данные, а также будет невозможно использовать программное обеспечение для восстановления, такое как https://ib-aid.com/en/ibsurgeon-firstaid/[FirstAID], для извлечения данных. Конечно, это зависит от алгоритма шифрования и вычислительной мощности, но взлом AES256 потребует слишком много времени или слишком больших вычислительных ресурсов.

. Для защиты базы данных от доступа неавторизованных приложений без ключей шифрования. Примеры:
прямой доступ с помощью инструментов разработчика неавторизованным лицом для изменения конфиденциальной информации (например, денежных транзакций), изменение или кража бизнес-логики (тексты хранимых процедур и триггеров).

. Защита баз данных с предварительно заполненными данными от экспорта или доступа неавторизованными приложениями.

. Недавно правительства ввели законы о защите данных (GDPR/DSVGO в Европе, LGPD в Бразилии и др.), которые требуют, среди прочего, более высокого уровня защиты персональных и других конфиденциальных данных, и шифрование упоминается как одна из адекватных мер защиты.

== Когда шифрование базы данных нецелесообразно?

В некоторых случаях лучше использовать возможности безопасности и настройки Firebird вместо шифрования базы данных:

. Для защиты базы данных от физического доступа по сети необходимо настроить сетевой доступ: то есть закрыть сетевые общие папки, поскольку Firebird не требует сетевого доступа к файлам базы данных, и ужесточить права доступа (например, для Linux файлы базы данных должны иметь доступ на чтение и запись только для пользователя и группы "`firebird`").

. Для ограничения доступа к конкретной базе данных для определенной группы пользователей более простым решением будет настройка отдельной базы данных безопасности.

. Для ограничения доступа к объектам базы данных (таблицам, хранимым процедурам) необходимо использовать механизмы безопасности Firebird: пользователи, роли и т. д.

Конечно, оба приведенных выше списка неполны, но они дают некоторое представление о том, когда вам нужно, а когда нет шифрование базы данных.

:sectnums:
