[[fbcrypt-keygen]]
= Генерация ключа

Для генерации ключей, которые могут быть использованы для шифрования мы разработали утилиту `aesKeyGen`, которые генерирует ключи для использования в алгоритме шифрования AES256. Использование утилиты тривиально

[source,cmd]
----
aesKeyGen.exe
----

для Linux команда выглядит следующим образом:

[source,bash]
----
./aesKeyGen
----

Вывод утилиты будет таким:

[listing]
----
const unsigned char aes256[] = {
0xd6,0xd8,0x8d,0x07,0x09,0x70,0xfe,0x8c,0x2e,0xfd,0xa2,0xee,0xcd,0x84,0xab,0xd3,0x89,0x48,0x29,0xa1,0x2b,0xf0,0xb9,0x81,0x65,0x2c,0xb2,0x92,0xad,0x22,0xb6,0xe1,
};
----

== Как использовать данный ключ?

=== В файле `KeyHolder.conf`

Этот файл может использоваться только для целей отладки.

Формат сохранения ключа следующий:

[source,cmd]
----
Key=<KeyName> <key_value>

<key_value> ::= 0x<hex-pair>, [0x<hex-pair>, ...]
----

У каждого ключа есть имя, которое записывается после `Key=`. Далее после отступа следует сам ключ, длинной 32-байта. Каждый байт записывается как 16-ричная пара. Каждый байт отделяется запятой. Конечная запятая обязательна.

=== В утилитах командной строки с плагином KeyHolderStdin

Общий формат вызова утилит командной строки с плагином `KeyHolderStdin` следующий:

[source,cmd]
----
echo Key=<KeyName> <key_value> | <utils> -KeyHolder KeyHolderStdin ...

<key_value> ::= 0x<hex-pair>, [0x<hex-pair>, ...]
----

Подробнее см. <<fbcrypt-utils>>.

=== В приложении на С/С++

Сгенерированный ключ можно взять как есть, удалив завершающую запятую.

[source,cpp]
----
const unsigned char aes256[] = {
0xd6,0xd8,0x8d,0x07,0x09,0x70,0xfe,0x8c,0x2e,0xfd,0xa2,0xee,0xcd,0x84,0xab,0xd3,0x89,0x48,0x29,0xa1,0x2b,0xf0,0xb9,0x81,0x65,0x2c,0xb2,0x92,0xad,0x22,0xb6,0xe1
};
----

=== В приложении на Delphi

Здесь всё достаточно просто, достаточно заменить все символы ключа `0x` на `$`.

[source,delphi]
----
const keyRed: array [0..31] of byte  = ($d6,$d8,$8d,$07,$09,$70,$fe,$8c,$2e,$fd,$a2,$ee,$cd,$84,$ab,$d3,$89,$48,$29,$a1,$2b,$f0,$b9,$81,$65,$2c,$b2,$92,$ad,$22,$b6,$e1);
----
